version: "3.4"

services:

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    networks:
      - network

  chat-app-client:
    image: row248/chat-app-client
    ports:
      - 3000:80
    networks:
      - network

  chat-app-backend:
    image: row248/chat-app-backend
    restart: always
    ports:
      - 3001:3000
    networks:
      - network

  chat-app-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - chat-app-db:/postgres/data:rw
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - network

volumes:
  chat-app-db:

networks:
  network:
    driver: bridge
