version: "3.4"

services:
  nginx:
    image: nginx
    container_name: nginx
#    volumes:
#      - ./nginx:/etc/nginx:rw
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80